/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_harman_adasvideo */

#ifndef _Included_com_harman_adasvideo
#define _Included_com_harman_adasvideo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_harman_adasvideo
 * Method:    enableGuideLine
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_harman_adasvideo_enableGuideLine
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_harman_adasvideo
 * Method:    setPreviewSurface
 * Signature: (Landroid/view/Surface;)V
 */
JNIEXPORT void JNICALL Java_com_harman_adasvideo_setPreviewSurface
  (JNIEnv *, jobject, jobject);

/*
 * Class:     com_harman_adasvideo
 * Method:    startPreview
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_harman_adasvideo_startPreview
  (JNIEnv *, jobject);

/*
 * Class:     com_harman_adasvideo
 * Method:    showGuideLine
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_harman_adasvideo_showGuideLine
  (JNIEnv *, jobject);

/*
 * Class:     com_harman_adasvideo
 * Method:    connect
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_com_harman_adasvideo_connect
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
